#Make sure to run the cpp program before running this python script as this script uses the CSVs generated by the CPP program 


import matplotlib.pyplot
import csv

from numpy import PINF, DataSource

#Opening the two CSV files created during C++ execution
csv_file = open("DES.csv")
dist_csv = open("inf_dist.csv")

#Using titles to skip over the headers of both the csv's
titles = []
titles = next(csv_file)
titles = next(dist_csv)

#rows contain the rows of the csv_file
rows = []
for i in csv_file:
    rows.append(i)

#dist_rows contain the rows of dist_csv
dist_rows = []
for i in dist_csv:
    dist_rows.append(i)

#Lists distance and inf_avg to store the individual distances and inf times of each rows in dist_rows
distance = []
inf_avg = []

#Making dist_rows a list of list of inf time and distances
for i in dist_rows:
    i = i.split(",")
    distance.append(int(i[1]))

for i in range(len(dist_rows)):
    dist_rows[i] = dist_rows[i].split(",")

#Removing duplicate records from distance since we want one inf_total per distance
distance = list(dict.fromkeys(distance))

#Calculating average inf_times for a particular distances and storing in inf_avg list
sum = 0
count = 0
for i in distance:
    sum = count = 0
    for j in dist_rows:
        if i == int(j[1]):
            sum = sum + int(j[0])
            count = count + 1
    inf_avg.append(sum/count)


time_stamp = []
S = []
I = []
R = []

#Storing time stamp and S,I,R of each row of rows in separate lists
for i in rows:
    i = i.split(",")
    time_stamp.append(int(i[0]))
    S.append(int(i[1]))
    I.append(int(i[2]))
    R.append(int(i[3]))

#Now we create a subplot of row = 1 and column = 4 and plot the graphs in their positions and output them finally
#Xlabel changes the X axis's label for a corresponding graph
#title changes the title of the graph



matplotlib.pyplot.subplot(1,4,1)
matplotlib.pyplot.title("Susceptible")
matplotlib.pyplot.xlabel("Time")
matplotlib.pyplot.ylabel("Susceptible Count")
matplotlib.pyplot.plot(time_stamp,S)

matplotlib.pyplot.subplot(1,4,2)
matplotlib.pyplot.title("Infected")
matplotlib.pyplot.xlabel("Time")
matplotlib.pyplot.ylabel("Infected Count")
matplotlib.pyplot.plot(time_stamp,I)

matplotlib.pyplot.subplot(1,4,3)
matplotlib.pyplot.title("Recovered")
matplotlib.pyplot.xlabel("Time")
matplotlib.pyplot.ylabel("Recovered Count")
matplotlib.pyplot.plot(time_stamp,R)

matplotlib.pyplot.subplot(1,4,4)
matplotlib.pyplot.title("Dist Vs Inf_time")
matplotlib.pyplot.xlabel("Distance")
matplotlib.pyplot.ylabel("Inf_time")
matplotlib.pyplot.plot(distance,inf_avg)

#Show outputs all the graphs
matplotlib.pyplot.show()